name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]  # or master, depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /var/www/html
          git pull origin main
          sudo chown -R www-data:www-data /var/www/html